name: 'OtakEmas'
description: A new Flutter project for PMO Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  supercharged: ^2.0.0
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  intl: ^0.17.0
  equatable: ^2.0.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  url_launcher: ^6.0.9
  platform: ^3.1.0
  shared_preferences: ^2.1.1
  card_swiper: ^2.0.4
  flutter_launcher_icons: ^0.10.0
  flutter_youtube_view: ^2.0.0
  table_calendar: ^3.0.0
  flutter_colorpicker: ^0.5.0
  hijri: ^3.0.0
  build_runner: ^2.4.4
  fluttertoast: ^8.0.7
  objectbox_generator: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/logo.png
    - assets/image/logo-only.png
    - assets/image/title.png
    - assets/image/otak.png
    - assets/image/daily-task.png
    - assets/image/motivasi.png
    - assets/image/panduan-islami.png
    - assets/image/workout.png
    - assets/image/dzikir-pagi.png
    - assets/image/dzikir-petang.png
    - assets/image/panduan-islami-dzikir.png
    - assets/image/panduan-islami-kalender-puasa.png
    - assets/image/finish.png
    - assets/image/workout-1.png
    - assets/image/workout-2.png
    - assets/image/workout-3.png
    - assets/image/onboarding-1.png
    - assets/image/onboarding-2.png
    - assets/image/onboarding-3.png
    - assets/image/badge-check.png
    - assets/image/history.png
    - assets/image/otak-day-1.png
    - assets/image/otak-day-3.png
    - assets/image/otak-day-7.png
    - assets/image/otak-day-15.png
    - assets/image/otak-day-30.png
    - assets/image/otak-day-90.png
